/**
 * gen-types.ts — OpenAPI → TypeScript 类型生成脚本
 *
 * 用法：
 *   npx tsx scripts/gen-types.ts --service auth       # 仅生成 auth-service 类型
 *   npx tsx scripts/gen-types.ts --all                # 生成所有服务类型
 *   npx tsx scripts/gen-types.ts --service auth --port 3001   # 指定端口
 *
 * 前置条件：目标微服务已启动并暴露 /api/docs-json 端点。
 *
 * 生成位置：
 *   - apps/miniprogram/src/types/generated/<service>.ts
 *   - apps/admin-web/src/types/generated/<service>.ts
 *
 * 注意：生成类型为纯类型导出（interface/type），零运行时依赖，
 * 与 Taro 小程序打包兼容。
 */
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT = path.resolve(__dirname, '..')

/** 服务端口映射（与 main.ts 默认端口对齐） */
const SERVICE_PORTS: Record<string, number> = {
  'auth-service': 3001,
  'user-service': 3002,
  'asset-service': 3003,
  'benchmark-service': 3004,
  'template-service': 3005,
  'billing-service': 3006,
  'workbench-service': 3007,
  'notification-service': 3008,
  'order-service': 3009,
  'admin-service': 3011,
}

/** 服务短名（去掉 -service 后缀，用作生成文件名） */
function shortName(service: string): string {
  return service.replace(/-service$/, '')
}

/** 解析命令行参数 */
function parseArgs(): { service?: string; all: boolean; port?: number } {
  const args = process.argv.slice(2)
  let service: string | undefined
  let all = false
  let port: number | undefined

  for (let i = 0; i < args.length; i++) {
    const arg = args[i]
    if (arg === '--service' || arg === '-s') {
      service = args[++i]
    } else if (arg === '--all' || arg === '-a') {
      all = true
    } else if (arg === '--port' || arg === '-p') {
      port = Number(args[++i])
    } else if (arg === '--help' || arg === '-h') {
      console.log(
        [
          '用法: npx tsx scripts/gen-types.ts [选项]',
          '',
          '选项:',
          '  -s, --service <name>   仅生成指定服务（如 auth-service 或 auth）',
          '  -a, --all              生成所有服务',
          '  -p, --port <port>      指定端口（仅与 --service 配合使用）',
          '  -h, --help             显示帮助',
          '',
          '示例:',
          '  npx tsx scripts/gen-types.ts --service auth-service',
          '  npx tsx scripts/gen-types.ts --service auth --port 3001',
          '  npx tsx scripts/gen-types.ts --all',
        ].join('\n'),
      )
      process.exit(0)
    }
  }

  return { service, all, port }
}

/** 规范化服务名（支持短名 → 全名） */
function normalizeServiceName(name: string): string {
  if (SERVICE_PORTS[name]) return name
  // 尝试补 -service 后缀
  const full = `${name}-service`
  if (SERVICE_PORTS[full]) return full
  throw new Error(`未知服务名: ${name}。可用服务: ${Object.keys(SERVICE_PORTS).join(', ')}`)
}

/** 拉取 OpenAPI JSON */
async function fetchOpenApiJson(url: string): Promise<unknown> {
  const res = await fetch(url)
  if (!res.ok) {
    throw new Error(`拉取 ${url} 失败: HTTP ${res.status} ${res.statusText}`)
  }
  return res.json()
}

/** 生成 TypeScript 类型文件内容 */
async function generateTypesAst(openapiSchema: unknown): Promise<string> {
  const ast = await openapiTS(openapiSchema as any)
  const code = astToString(ast)
  // 在文件头部添加生成信息
  const header = [
    '/**',
    ' * AUTO-GENERATED by scripts/gen-types.ts — 请勿手工修改',
    ` * Generated at: ${new Date().toISOString()}`,
    ' * Source: OpenAPI schema from backend service',
    ' *',
    ' * 修改方式：调整后端 DTO/Controller 的 @ApiProperty 装饰器，',
    ' * 然后重新运行 `npm run gen:types`。',
    ' */',
    '',
  ].join('\n')
  return header + code
}

/** 确保目录存在 */
async function ensureDir(dir: string): Promise<void> {
  await fs.mkdir(dir, { recursive: true })
}

/** 写入生成文件 */
async function writeGeneratedFile(serviceName: string, code: string): Promise<void> {
  const short = shortName(serviceName)
  const targets = [
    path.join(ROOT, 'apps/miniprogram/src/types/generated'),
    path.join(ROOT, 'apps/admin-web/src/types/generated'),
  ]

  for (const dir of targets) {
    await ensureDir(dir)
    const filePath = path.join(dir, `${short}.ts`)
    await fs.writeFile(filePath, code, 'utf8')
    console.log(`  ✓ ${path.relative(ROOT, filePath)}`)
  }
}

/** 处理单个服务 */
async function processService(serviceName: string, customPort?: number): Promise<boolean> {
  const port = customPort ?? SERVICE_PORTS[serviceName]
  if (!port) {
    console.error(`✗ ${serviceName}: 未知端口`)
    return false
  }

  const url = `http://localhost:${port}/api/docs-json`
  console.log(`\n→ ${serviceName} (${url})`)

  try {
    const schema = await fetchOpenApiJson(url)
    const code = await generateTypesAst(schema)
    await writeGeneratedFile(serviceName, code)
    console.log(`✓ ${serviceName} 类型生成完成`)
    return true
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error(`✗ ${serviceName} 生成失败: ${msg}`)
    console.error(
      `  请确认服务已启动: cd apps/${serviceName} && npm run serve (或 PORT=${port} npm start)`,
    )
    return false
  }
}

/** 生成 index.ts 汇总导出 */
async function generateIndexFile(services: string[], succeeded: string[]): Promise<void> {
  const targets = [
    path.join(ROOT, 'apps/miniprogram/src/types/generated'),
    path.join(ROOT, 'apps/admin-web/src/types/generated'),
  ]

  for (const dir of targets) {
    await ensureDir(dir)
    const lines: string[] = [
      '/**',
      ' * AUTO-GENERATED index.ts — 请勿手工修改',
      ` * Generated at: ${new Date().toISOString()}`,
      ' *',
      ' * 汇总导出所有服务的生成类型。',
      ' */',
      '',
    ]
    for (const svc of succeeded) {
      const short = shortName(svc)
      lines.push(`export * as ${short.replace(/-/g, '_')} from './${short}'`)
    }
    lines.push('')
    const filePath = path.join(dir, 'index.ts')
    await fs.writeFile(filePath, lines.join('\n'), 'utf8')
    console.log(`  ✓ ${path.relative(ROOT, filePath)}`)
  }

  const failed = services.filter((s) => !succeeded.includes(s))
  if (failed.length > 0) {
    console.log(`\n⚠ ${failed.length} 个服务生成失败: ${failed.join(', ')}`)
    console.log('  index.ts 仅汇总成功的服务，失败服务需单独重跑')
  }
}

async function main(): Promise<void> {
  const { service, all, port } = parseArgs()

  if (!service && !all) {
    console.error('错误: 必须指定 --service <name> 或 --all')
    console.error('使用 --help 查看帮助')
    process.exit(1)
  }

  const services: string[] = all ? Object.keys(SERVICE_PORTS) : [normalizeServiceName(service!)]

  console.log(`\n🚀 开始生成 TypeScript 类型 (${services.length} 个服务)`)
  console.log('='.repeat(60))

  const succeeded: string[] = []
  for (const svc of services) {
    const ok = await processService(svc, all ? undefined : port)
    if (ok) succeeded.push(svc)
  }

  console.log('\n' + '='.repeat(60))
  console.log(`📦 生成汇总 index.ts`)
  await generateIndexFile(services, succeeded)

  console.log('\n' + '='.repeat(60))
  console.log(`✅ 完成: ${succeeded.length}/${services.length} 成功`)
  if (succeeded.length < services.length) {
    process.exit(1)
  }
}

main().catch((err) => {
  console.error('❌ 生成失败:', err)
  process.exit(1)
})
