/**
 * gen-types-local.ts — 本地 OpenAPI JSON → TypeScript 类型（离线验证脚本）
 *
 * 用途：当无法启动 NestJS 服务时，从本地 JSON 文件生成类型，
 *      验证 openapi-typescript 工具链可用性。
 *
 * 用法：
 *   npx tsx scripts/gen-types-local.ts scripts/fixtures/auth-service.openapi.json
 */
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT = path.resolve(__dirname, '..')

async function main(): Promise<void> {
  const inputFile = process.argv[2]
  if (!inputFile) {
    console.error('用法: npx tsx scripts/gen-types-local.ts <openapi-json-path>')
    process.exit(1)
  }

  const absInput = path.isAbsolute(inputFile) ? inputFile : path.resolve(ROOT, inputFile)
  console.log(`→ 读取 OpenAPI JSON: ${absInput}`)

  const raw = await fs.readFile(absInput, 'utf8')
  const schema = JSON.parse(raw)

  // 用 source 文件内容的 SHA256 前 12 位作为稳定标识，替代时间戳。
  // 这样 source 不变 → 生成文件完全不变 → CI 一致性校验可靠。
  const sourceHash = crypto.createHash('sha256').update(raw).digest('hex').slice(0, 12)

  console.log(`→ 生成 TypeScript 类型... (source hash: ${sourceHash})`)
  const ast = await openapiTS(schema as any)
  const code = astToString(ast)

  const header = [
    '/**',
    ' * AUTO-GENERATED by scripts/gen-types-local.ts — 请勿手工修改',
    ` * Source: ${path.relative(ROOT, absInput)}`,
    ` * Source hash: ${sourceHash}`,
    ' */',
    '',
  ].join('\n')
  const fullCode = header + code

  // 写入 miniprogram 与 admin-web 的 generated 目录
  const serviceName = path.basename(absInput, '.openapi.json').replace(/-service$/, '')
  const targets = [
    path.join(ROOT, 'apps/miniprogram/src/types/generated'),
    path.join(ROOT, 'apps/admin-web/src/types/generated'),
  ]

  for (const dir of targets) {
    await fs.mkdir(dir, { recursive: true })
    const filePath = path.join(dir, `${serviceName}.ts`)
    await fs.writeFile(filePath, fullCode, 'utf8')
    console.log(`  ✓ ${path.relative(ROOT, filePath)}`)
  }

  // 生成 index.ts（不含时间戳，保证 source 不变则文件完全不变）
  for (const dir of targets) {
    const indexPath = path.join(dir, 'index.ts')
    const existing = await fs.readdir(dir).catch(() => [])
    const exports = existing
      .filter((f) => f.endsWith('.ts') && f !== 'index.ts')
      .map((f) => {
        const name = path.basename(f, '.ts').replace(/-/g, '_')
        return `export * as ${name} from './${path.basename(f, '.ts')}'`
      })
    const indexContent = [
      '/**',
      ' * AUTO-GENERATED index.ts — 请勿手工修改',
      ` * Source hash: ${sourceHash}`,
      ' */',
      '',
      ...exports,
      '',
    ].join('\n')
    await fs.writeFile(indexPath, indexContent, 'utf8')
    console.log(`  ✓ ${path.relative(ROOT, indexPath)}`)
  }

  console.log(`\n✅ 类型生成完成`)
}

main().catch((err) => {
  console.error('❌ 生成失败:', err)
  process.exit(1)
})
