/**
 * gen-types-local.ts — 本地 OpenAPI JSON → TypeScript 类型（批量生成）
 *
 * 用途：从 scripts/fixtures/*.openapi.json 生成前端 TypeScript 类型，
 *      写入 miniprogram 与 admin-web 的 src/types/generated/ 目录。
 *
 * 用法：
 *   # 生成所有服务（默认）
 *   npm run gen:types
 *
 *   # 生成单个服务
 *   npx tsx scripts/gen-types-local.ts scripts/fixtures/auth-service.openapi.json
 *
 * 确定性保证（CI 一致性校验）：
 *   - source 文件内容 SHA256 前 12 位作为稳定标识，替代时间戳
 *   - source 不变 → 生成文件完全不变 → git diff --exit-code 可靠
 */
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT = path.resolve(__dirname, '..')

const FIXTURES_DIR = path.join(ROOT, 'scripts', 'fixtures')
const TARGETS = [
  path.join(ROOT, 'apps/miniprogram/src/types/generated'),
  path.join(ROOT, 'apps/admin-web/src/types/generated'),
]

interface ServiceFile {
  /** 绝对路径 */
  abs: string
  /** 服务名（去掉 -service 后缀，如 auth / user / admin） */
  name: string
  /** 原始 JSON 内容 */
  raw: string
  /** 源文件 SHA256 前 12 位 */
  hash: string
}

/** 收集所有 OpenAPI JSON fixture */
async function collectFixtures(singleFile?: string): Promise<ServiceFile[]> {
  const files: ServiceFile[] = []

  if (singleFile) {
    const abs = path.isAbsolute(singleFile) ? singleFile : path.resolve(ROOT, singleFile)
    const raw = await fs.readFile(abs, 'utf8')
    const hash = crypto.createHash('sha256').update(raw).digest('hex').slice(0, 12)
    const name = path.basename(abs, '.openapi.json').replace(/-service$/, '')
    files.push({ abs, name, raw, hash })
    return files
  }

  const entries = await fs.readdir(FIXTURES_DIR)
  for (const entry of entries) {
    if (!entry.endsWith('.openapi.json')) continue
    const abs = path.join(FIXTURES_DIR, entry)
    const raw = await fs.readFile(abs, 'utf8')
    const hash = crypto.createHash('sha256').update(raw).digest('hex').slice(0, 12)
    const name = path.basename(abs, '.openapi.json').replace(/-service$/, '')
    files.push({ abs, name, raw, hash })
  }

  // 按服务名排序，保证生成顺序确定
  files.sort((a, b) => a.name.localeCompare(b.name))
  return files
}

/** 为单个服务生成类型文件 */
async function generateServiceTypes(service: ServiceFile, targetDir: string): Promise<string> {
  const schema = JSON.parse(service.raw)
  const ast = await openapiTS(schema as any)
  const code = astToString(ast)

  const header = [
    '/**',
    ' * AUTO-GENERATED by scripts/gen-types-local.ts — 请勿手工修改',
    ` * Source: ${path.relative(ROOT, service.abs)}`,
    ` * Source hash: ${service.hash}`,
    ' */',
    '',
  ].join('\n')

  const fullCode = header + code
  const filePath = path.join(targetDir, `${service.name}.ts`)
  await fs.mkdir(path.dirname(filePath), { recursive: true })
  await fs.writeFile(filePath, fullCode, 'utf8')
  return filePath
}

/** 生成 index.ts（汇总所有服务的 re-export，不含时间戳保证确定性） */
async function generateIndex(targetDir: string, serviceNames: string[]): Promise<void> {
  const exports = serviceNames.sort().map((name) => {
    const ident = name.replace(/-/g, '_')
    return `export * as ${ident} from './${name}'`
  })

  const content = [
    '/**',
    ' * AUTO-GENERATED index.ts — 请勿手工修改',
    ` * Services: ${serviceNames.sort().join(', ')}`,
    ' */',
    '',
    ...exports,
    '',
  ].join('\n')

  const indexPath = path.join(targetDir, 'index.ts')
  await fs.writeFile(indexPath, content, 'utf8')
}

async function main(): Promise<void> {
  const singleFile = process.argv[2]
  const isBatch = !singleFile

  console.log(
    isBatch ? '🚀 批量生成所有服务的 TypeScript 类型' : `🚀 生成单个服务类型: ${singleFile}`,
  )
  console.log('============================================================')

  const services = await collectFixtures(singleFile)
  if (services.length === 0) {
    console.error('❌ 未找到任何 OpenAPI JSON fixture')
    process.exit(1)
  }

  console.log(`\n📦 共 ${services.length} 个服务`)

  for (const target of TARGETS) {
    console.log(`\n→ 写入目录: ${path.relative(ROOT, target)}`)
    await fs.mkdir(target, { recursive: true })

    const generatedNames: string[] = []
    for (const service of services) {
      const filePath = await generateServiceTypes(service, target)
      console.log(`  ✓ ${path.relative(ROOT, filePath)} (hash: ${service.hash})`)
      generatedNames.push(service.name)
    }

    await generateIndex(target, generatedNames)
    console.log(`  ✓ index.ts (${generatedNames.length} services)`)
  }

  console.log('\n✅ 类型生成完成')
}

main().catch((err) => {
  console.error('❌ 生成失败:', err)
  process.exit(1)
})
